model:
  name: klue/bert-base

dataset:
  train_path: ./data/train_dataset
  context_path: ./data/wikipedia_documents.json

seed: 42

faiss:
  use: False
  num_clusters: 64

training:
  output_dir: dense_output
  epochs: 5
  learning_rate: 2e-5
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 8
  num_negative: 8
  weight_decay: 0.01
  use_tfidf_negative_sampling: False  # TF-IDF 기반 네거티브 샘플링 사용 여부
