_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 100
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.5
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
dataQA:
    value: |
        config.null
        ...
dataRetrieval:
    value: |
        config.null
        ...
model:
    value: |
        config.null
        ...
output:
    value: |
        config.null
        ...
peft:
    value: |
        config.null
        ...
seed:
    value: |
        config.null
        ...
testing:
    value: |
        config.null
        ...
training:
    value: |
        config.null
        ...
